// <auto-generated />
using System;
using FooBackBar.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FooBackBar.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20201029133526_CountryStatusAdded")]
    partial class CountryStatusAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("FooBackBar.Models.CaseHistory", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GuidCountry")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GuidStatus")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("GuidCountry");

                    b.HasIndex("GuidStatus");

                    b.ToTable("CaseHistories");
                });

            modelBuilder.Entity("FooBackBar.Models.Coordinates", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GuidCountry")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("GuidCountry")
                        .IsUnique();

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("FooBackBar.Models.Country", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("FooBackBar.Models.CountryStatus", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GuidCountry")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GuidStatus")
                        .HasColumnType("TEXT");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.HasIndex("GuidCountry");

                    b.HasIndex("GuidStatus");

                    b.ToTable("CountryStatus");
                });

            modelBuilder.Entity("FooBackBar.Models.Status", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeath")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecovered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("e0000fa0-3ccf-456d-8623-9d9199ae163d"),
                            IsConfirmed = true,
                            IsDeath = false,
                            IsRecovered = false,
                            Total = 0
                        },
                        new
                        {
                            Guid = new Guid("7e3eae76-bd12-4927-845a-974f24bfd4c9"),
                            IsConfirmed = false,
                            IsDeath = true,
                            IsRecovered = false,
                            Total = 0
                        },
                        new
                        {
                            Guid = new Guid("7aff6beb-fda3-4903-9d4e-168e732179d2"),
                            IsConfirmed = false,
                            IsDeath = false,
                            IsRecovered = true,
                            Total = 0
                        });
                });

            modelBuilder.Entity("FooBackBar.Models.CaseHistory", b =>
                {
                    b.HasOne("FooBackBar.Models.Country", "Country")
                        .WithMany("History")
                        .HasForeignKey("GuidCountry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FooBackBar.Models.Status", "Status")
                        .WithMany("CaseHistories")
                        .HasForeignKey("GuidStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FooBackBar.Models.Coordinates", b =>
                {
                    b.HasOne("FooBackBar.Models.Country", "Country")
                        .WithOne("Coordinates")
                        .HasForeignKey("FooBackBar.Models.Coordinates", "GuidCountry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FooBackBar.Models.CountryStatus", b =>
                {
                    b.HasOne("FooBackBar.Models.Country", "Country")
                        .WithMany("CountryStatus")
                        .HasForeignKey("GuidCountry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FooBackBar.Models.Status", "Status")
                        .WithMany("CountryStatus")
                        .HasForeignKey("GuidStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
