// <auto-generated />
using System;
using FooBackBar.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FooBackBar.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200929233708_StatusSeeds")]
    partial class StatusSeeds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("FooBackBar.Models.CaseHistory", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GuidCountry")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GuidStatus")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("GuidCountry");

                    b.HasIndex("GuidStatus");

                    b.ToTable("CaseHistories");
                });

            modelBuilder.Entity("FooBackBar.Models.Coordinates", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GuidCountry")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("GuidCountry")
                        .IsUnique();

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("FooBackBar.Models.Country", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("FooBackBar.Models.Status", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeath")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecovered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("2313ee8a-47ed-4a4f-94ac-35382658b3d0"),
                            IsConfirmed = true,
                            IsDeath = false,
                            IsRecovered = false,
                            Total = 0
                        },
                        new
                        {
                            Guid = new Guid("04f7ce06-59fb-4cfa-ae87-0f5a3f604d7e"),
                            IsConfirmed = false,
                            IsDeath = true,
                            IsRecovered = false,
                            Total = 0
                        },
                        new
                        {
                            Guid = new Guid("3ea1615d-c001-48a8-b650-5875e0a1ec9b"),
                            IsConfirmed = false,
                            IsDeath = false,
                            IsRecovered = true,
                            Total = 0
                        });
                });

            modelBuilder.Entity("FooBackBar.Models.CaseHistory", b =>
                {
                    b.HasOne("FooBackBar.Models.Country", "Country")
                        .WithMany("History")
                        .HasForeignKey("GuidCountry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FooBackBar.Models.Status", "Status")
                        .WithMany("CaseHistories")
                        .HasForeignKey("GuidStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FooBackBar.Models.Coordinates", b =>
                {
                    b.HasOne("FooBackBar.Models.Country", "Country")
                        .WithOne("Coordinates")
                        .HasForeignKey("FooBackBar.Models.Coordinates", "GuidCountry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
